### ISSUE TITLE
Error with models

### ISSUE THREAD

**Issue by jordanlanch** [SwayamInSync/clothes-virtual-try-on#29]
Hi, I have this error when I try to compile in a dockerfile

dockerfile
```
# Base image with CUDA and cuDNN
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

# Set non-interactive frontend (to avoid some prompts)
ENV DEBIAN_FRONTEND noninteractive
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES video,compute,utility
ENV TZ=America/New_York

# Install essential tools and libraries
RUN apt-get update && apt-get install -y \
    git \
    wget \
    build-essential \
    ffmpeg \
    libatlas-base-dev \
    libprotobuf-dev \
    libleveldb-dev \
    libsnappy-dev \
    libhdf5-serial-dev \
    protobuf-compiler \
    libboost-all-dev \
    libgflags-dev \
    libgoogle-glog-dev \
    liblmdb-dev \
    opencl-headers \
    ocl-icd-opencl-dev \
    libviennacl-dev \
    libopencv-dev \
    ca-certificates \
    python3-setuptools \
    python3-dev \
    build-essential \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean


# Install OpenSSL
ARG OPENSSL_VERSION=1.1.1l
RUN wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz \
    && tar xvfz openssl-${OPENSSL_VERSION}.tar.gz \
    && cd openssl-${OPENSSL_VERSION} \
    && ./config --prefix=/usr/local --openssldir=/usr/local/ssl --libdir=lib shared zlib-dynamic \
    && make \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf openssl-${OPENSSL_VERSION} \
    && rm openssl-${OPENSSL_VERSION}.tar.gz

# Clone OpenPose repository with the specific version
WORKDIR /content
RUN wget --no-check-certificate -c "https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6.tar.gz" && tar xf cmake-3.19.6.tar.gz
# Upgrade CMake to version 3.19.6
RUN cd cmake-3.19.6 && ./configure && make && make install && rm -rf cmake-3.19.6

RUN git clone  --depth 1 -b "v1.7.0" https://github.com/CMU-Perceptual-Computing-Lab/openpose.git --recursive

COPY ./openpose/models/face/pose_iter_116000.caffemodel /content/openpose/models/face/pose_iter_116000.caffemodel

COPY ./openpose/models/hand/pose_iter_102000.caffemodel /content/openpose/models/hand/pose_iter_102000.caffemodel
COPY ./openpose/models/hand/pose_iter_120000.caffemodel /content/openpose/models/hand/pose_iter_120000.caffemodel

COPY ./openpose/models/pose/1_25BBkg/body_25b/pose_iter_810000.caffemodel /content/openpose/models/pose/1_25BBkg/body_25/pose_iter_810000.caffemodel
COPY ./openpose/models/pose/1_25BBkg/body_25b/pose_iter_XXXXXX.caffemodel /content/openpose/models/pose/1_25BBkg/body_25b/pose_iter_XXXXXX.caffemodel
COPY ./openpose/models/pose/1_25BBkg/body_25b/training_log.txt /content/openpose/models/pose/1_25BBkg/body_25b/training_log.txt

COPY ./openpose/models/pose/1_25BSuperModel11FullVGG/body_25b/pose_iter_636000.caffemodel /content/openpose/models/pose/1_25BSuperModel11FullVGG/body_25b/pose_iter_636000.caffemodel
COPY ./openpose/models/pose/1_25BSuperModel11FullVGG/body_25b/pose_iter_XXXXXX.caffemodel /content/openpose/models/pose/1_25BSuperModel11FullVGG/body_25b/pose_iter_XXXXXX.caffemodel
COPY ./openpose/models/pose/1_25BSuperModel11FullVGG/body_25b/training_log.txt /content/openpose/models/pose/1_25BSuperModel11FullVGG/body_25b/training_log.txt

COPY ./openpose/models/pose/2_25YaserWholeBatch/obtain_from_body_25_details_inside_txt.txt /content/openpose/models/pose/2_25YaserWholeBatch/obtain_from_body_25_details_inside_txt.txt

COPY ./openpose/models/pose/100_135AlmostSameBatchAllGPUs/body_135/pose_iter_464000.caffemodel /content/openpose/models/pose/100_135AlmostSameBatchAllGPUs/body_135/pose_iter_464000.caffemodel
COPY ./openpose/models/pose/100_135AlmostSameBatchAllGPUs/body_135/pose_iter_XXXXXX.caffemodel /content/openpose/models/pose/100_135AlmostSameBatchAllGPUs/body_135/pose_iter_XXXXXX.caffemodel
COPY ./openpose/models/pose/100_135AlmostSameBatchAllGPUs/body_135/training_log.txt /content/openpose/models/pose/100_135AlmostSameBatchAllGPUs/body_135/training_log.txt

COPY ./openpose/models/pose/body_21a_video/pose_deploy.prototxt /content/openpose/models/pose/body_21a_video/pose_deploy.prototxt
COPY ./openpose/models/pose/body_21a_video/pose_iter_264000.caffemodel /content/openpose/models/pose/body_21a_video/pose_iter_264000.caffemodel

COPY ./openpose/models/pose/body_25/pose_iter_584000.caffemodel /content/openpose/models/pose/body_25/pose_iter_584000.caffemodel
COPY ./openpose/models/pose/body_25/training_log.txt /content/openpose/models/pose/body_25/training_log.txt
COPY ./openpose/models/pose/body_25/training_results_source.txt /content/openpose/models/pose/body_25/training_results_source.txt

COPY ./openpose/models/pose/coco/main.html /content/openpose/models/pose/coco/main.html
COPY ./openpose/models/pose/coco/pose_iter_440000.caffemodel /content/openpose/models/pose/coco/pose_iter_440000.caffemodel

COPY ./openpose/models/pose/mpi/pose_iter_160000.caffemodel /content/openpose/models/pose/mpi/pose_iter_160000.caffemodel


# Configure and build OpenPose
WORKDIR /content/openpose/build
RUN cmake -DUSE_CUDNN=OFF -DBUILD_PYTHON=ON .. \
    && make -j`nproc`

# Install other Python packages
RUN pip3 install ninja

WORKDIR /content
RUN git clone https://github.com/practice404/clothes-virtual-try-on.git
RUN cd clothes-virtual-try-on && mkdir checkpoints
COPY ./clothes-virtual-try-on/checkpoints /content/clothes-virtual-try-on/checkpoints
COPY ./clothes-virtual-try-on/app.py /content/clothes-virtual-try-on/app.py
COPY ./clothes-virtual-try-on/cloth_segm_u2net_latest.pth /content/clothes-virtual-try-on/cloth_segm_u2net_latest.pth

RUN git clone https://github.com/PeikeLi/Self-Correction-Human-Parsing
RUN cd Self-Correction-Human-Parsing && mkdir checkpoints
COPY ./Self-Correction-Human-Parsing/checkpoints /content/Self-Correction-Human-Parsing/checkpoints


WORKDIR /content
# Install Miniconda
ENV MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh
ENV MINICONDA_PREFIX=/usr/local
RUN wget --no-check-certificate https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT \
    && chmod +x $MINICONDA_INSTALLER_SCRIPT \
    && ./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX \
    && conda install --channel defaults conda python=3.8 --yes \
    && conda update --channel defaults --all --yes

# Install PyTorch compatible with CUDA 11.7
RUN pip install torch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 -f https://download.pytorch.org/whl/torch_stable.html

# Install other Python packages
RUN pip install Flask gdown rembg[gpu] gradio==3.45.0 numpy protobuf torchgeometry opencv-python torchvision Pillow

# Clone additional repositories and download models
WORKDIR /content
RUN nvcc --version
RUN cd /content/ && mkdir inputs && cd inputs && mkdir test && cd test && mkdir cloth cloth-mask image image-parse openpose-img openpose-json

# Set command to launch your application
CMD ["python", "/content/clothes-virtual-try-on/test.py", "--name", "outputs", "--dataset_dir", "/content/inputs", "--checkpoint_dir", "/content/clothes-virtual-try-on/checkpoints", "--save_dir", "/content/"]


```

error

```

==========
== CUDA ==
==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Namespace(alias_checkpoint='alias_final.pth', batch_size=1, checkpoint_dir='/content/clothes-virtual-try-on/checkpoints', dataset_dir='/content/inputs', dataset_list='test_pairs.txt', dataset_mode='test', display_freq=1, gmm_checkpoint='gmm_final.pth', grid_size=5, init_type='xavier', init_variance=0.02, load_height=1024, load_width=768, name='outputs', ngf=64, norm_G='spectralaliasinstance', num_upsampling_layers='most', save_dir='/content/', seg_checkpoint='seg_final.pth', semantic_nc=13, shuffle=False, workers=1)
Network [SegGenerator] was created. Total number of parameters: 34.5 million. To see the architecture, do print(network).
Network [ALIASGenerator] was created. Total number of parameters: 100.5 million. To see the architecture, do print(network).
Traceback (most recent call last):
  File "/content/clothes-virtual-try-on/test.py", line 155, in <module>
    main()
  File "/content/clothes-virtual-try-on/test.py", line 148, in main
    seg.cuda().eval()
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 747, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 662, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 747, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from hipGetDeviceCount(). Did you run some cuda functions before calling NumHipDevices() that might have already set an error? Error 101: hipErrorInvalidDevice
```

I just followed step by step  in you setup, but I don't know what is the problem

thanks

Run 

 docker build -t clothes-v .  && docker run --gpus all  clothes-v

**Comment by SwayamInSync** [comment]
If you're encountering this issue even after having CUDA device then I think it is maybe because cuDNN is not supported yet or creating another python environment with conda within dockerfile causing the issue.

I didn't try building its dockerfile yet because of openpose dependency (which will be resolved soon) till then I recommend to use the notebook as it is

**Comment by punithan328** [comment]
@SwayamInSync 

I'm getting tis error but one month before it worked perfectly what's the reason for this error 
2024-04-16 03:06:55 (108 MB/s) - ‘Miniconda3-4.5.4-Linux-x86_64.sh’ saved [58468498/58468498]

Python 3.6.5 :: Anaconda, Inc.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ /usr/local/bin/conda install --channel defaults conda python=3.8 --yes`

  environment variables:
                 CIO_TEST=<not set>
COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer
COLAB_LANGUAGE_SERVER_PROXY=<set>
               CONDA_ROOT=/usr/local
          LD_LIBRARY_PATH=/usr/lib64-nvidia
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us
                          r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl
                          e-cloud-sdk/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               TCLLIBPATH=/usr/share/tcltk/tcllib1.20

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /usr/local  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False


V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com/ blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",),))',),)

A reportable application error has occurred. Conda has prepared the above report.
Upload did not complete.
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ /usr/local/bin/conda update --channel defaults --all --yes`

  environment variables:
                 CIO_TEST=<not set>
COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer
COLAB_LANGUAGE_SERVER_PROXY=<set>
               CONDA_ROOT=/usr/local
          LD_LIBRARY_PATH=/usr/lib64-nvidia
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us
                          r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl
                          e-cloud-sdk/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               TCLLIBPATH=/usr/share/tcltk/tcllib1.20

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /usr/local  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False


V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/pro/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com/ blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/pro/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",),))',),)

A reportable application error has occurred. Conda has prepared the above report.
Upload did not complete.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-1-aec5c59d6b8f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('bash', '', 'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n')

4 frames
<decorator-gen-103> in shebang(self, line, cell)

[/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n'' returned non-zero exit status 1.2024-04-16 03:06:55 (108 MB/s) - ‘Miniconda3-4.5.4-Linux-x86_64.sh’ saved [58468498/58468498]

Python 3.6.5 :: Anaconda, Inc.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ /usr/local/bin/conda install --channel defaults conda python=3.8 --yes`

  environment variables:
                 CIO_TEST=<not set>
COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer
COLAB_LANGUAGE_SERVER_PROXY=<set>
               CONDA_ROOT=/usr/local
          LD_LIBRARY_PATH=/usr/lib64-nvidia
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us
                          r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl
                          e-cloud-sdk/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               TCLLIBPATH=/usr/share/tcltk/tcllib1.20

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /usr/local  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False


V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com/ blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",),))',),)

A reportable application error has occurred. Conda has prepared the above report.
Upload did not complete.
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ /usr/local/bin/conda update --channel defaults --all --yes`

  environment variables:
                 CIO_TEST=<not set>
COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer
COLAB_LANGUAGE_SERVER_PROXY=<set>
               CONDA_ROOT=/usr/local
          LD_LIBRARY_PATH=/usr/lib64-nvidia
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us
                          r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl
                          e-cloud-sdk/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               TCLLIBPATH=/usr/share/tcltk/tcllib1.20

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /usr/local  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False


V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/pro/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com/ blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/pro/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",),))',),)

A reportable application error has occurred. Conda has prepared the above report.
Upload did not complete.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-1-aec5c59d6b8f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('bash', '', 'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n')

4 frames
<decorator-gen-103> in shebang(self, line, cell)

[/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n'' returned non-zero exit status 1.

**Comment by sumit-jr** [comment]
> @SwayamInSync
> 
> I'm getting tis error but one month before it worked perfectly what's the reason for this error 2024-04-16 03:06:55 (108 MB/s) - ‘Miniconda3-4.5.4-Linux-x86_64.sh’ saved [58468498/58468498]
> 
> Python 3.6.5 :: Anaconda, Inc.
> 
> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> `$ /usr/local/bin/conda install --channel defaults conda python=3.8 --yes`
> 
> environment variables: CIO_TEST= COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer COLAB_LANGUAGE_SERVER_PROXY= CONDA_ROOT=/usr/local LD_LIBRARY_PATH=/usr/lib64-nvidia LIBRARY_PATH=/usr/local/cuda/lib64/stubs PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl e-cloud-sdk/bin PYTHONPATH=/env/python PYTHONWARNINGS=ignore:::pip._internal.cli.base_command REQUESTS_CA_BUNDLE= SSL_CERT_FILE= TCLLIBPATH=/usr/share/tcltk/tcllib1.20
> 
> ```
>  active environment : None
>    user config file : /root/.condarc
> ```
> 
> populated config files : conda version : 4.5.4 conda-build version : not installed python version : 3.6.5.final.0 base environment : /usr/local (writable) channel URLs : https://repo.anaconda.com/pkgs/main/linux-64 https://repo.anaconda.com/pkgs/main/noarch https://repo.anaconda.com/pkgs/free/linux-64 https://repo.anaconda.com/pkgs/free/noarch https://repo.anaconda.com/pkgs/r/linux-64 https://repo.anaconda.com/pkgs/r/noarch https://repo.anaconda.com/pkgs/pro/linux-64 https://repo.anaconda.com/pkgs/pro/noarch package cache : /usr/local/pkgs /root/.conda/pkgs envs directories : /usr/local/envs /root/.conda/envs platform : linux-64 user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35 UID:GID : 0:0 netrc file : None offline mode : False
> 
> V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://repo.anaconda.com/pkgs/main/noarch/repodata.json.bz2 Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> If your current network has https://www.anaconda.com/ blocked, please file a support request with your network engineering team.
> 
> SSLError(MaxRetryError('HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))',),)
> 
> A reportable application error has occurred. Conda has prepared the above report. Upload did not complete.
> 
> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> `$ /usr/local/bin/conda update --channel defaults --all --yes`
> 
> environment variables: CIO_TEST= COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer COLAB_LANGUAGE_SERVER_PROXY= CONDA_ROOT=/usr/local LD_LIBRARY_PATH=/usr/lib64-nvidia LIBRARY_PATH=/usr/local/cuda/lib64/stubs PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl e-cloud-sdk/bin PYTHONPATH=/env/python PYTHONWARNINGS=ignore:::pip._internal.cli.base_command REQUESTS_CA_BUNDLE= SSL_CERT_FILE= TCLLIBPATH=/usr/share/tcltk/tcllib1.20
> 
> ```
>  active environment : None
>    user config file : /root/.condarc
> ```
> 
> populated config files : conda version : 4.5.4 conda-build version : not installed python version : 3.6.5.final.0 base environment : /usr/local (writable) channel URLs : https://repo.anaconda.com/pkgs/main/linux-64 https://repo.anaconda.com/pkgs/main/noarch https://repo.anaconda.com/pkgs/free/linux-64 https://repo.anaconda.com/pkgs/free/noarch https://repo.anaconda.com/pkgs/r/linux-64 https://repo.anaconda.com/pkgs/r/noarch https://repo.anaconda.com/pkgs/pro/linux-64 https://repo.anaconda.com/pkgs/pro/noarch package cache : /usr/local/pkgs /root/.conda/pkgs envs directories : /usr/local/envs /root/.conda/envs platform : linux-64 user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35 UID:GID : 0:0 netrc file : None offline mode : False
> 
> V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://repo.anaconda.com/pkgs/pro/noarch/repodata.json.bz2 Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> If your current network has https://www.anaconda.com/ blocked, please file a support request with your network engineering team.
> 
> SSLError(MaxRetryError('HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/pro/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))',),)
> 
> ## A reportable application error has occurred. Conda has prepared the above report.
> Upload did not complete.
> CalledProcessError Traceback (most recent call last) in <cell line: 1>() ----> 1 get_ipython().run_cell_magic('bash', '', 'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n')
> 
> 4 frames in shebang(self, line, cell)
> 
> [/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell) 243 sys.stderr.flush() 244 if args.raise_error and p.returncode!=0: --> 245 raise CalledProcessError(p.returncode, cell, output=out, stderr=err) 246 247 def _run_script(self, p, cell, to_close):
> 
> CalledProcessError: Command 'b'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n'' returned non-zero exit status 1.2024-04-16 03:06:55 (108 MB/s) - ‘Miniconda3-4.5.4-Linux-x86_64.sh’ saved [58468498/58468498]
> 
> Python 3.6.5 :: Anaconda, Inc.
> 
> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> `$ /usr/local/bin/conda install --channel defaults conda python=3.8 --yes`
> 
> environment variables: CIO_TEST= COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer COLAB_LANGUAGE_SERVER_PROXY= CONDA_ROOT=/usr/local LD_LIBRARY_PATH=/usr/lib64-nvidia LIBRARY_PATH=/usr/local/cuda/lib64/stubs PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl e-cloud-sdk/bin PYTHONPATH=/env/python PYTHONWARNINGS=ignore:::pip._internal.cli.base_command REQUESTS_CA_BUNDLE= SSL_CERT_FILE= TCLLIBPATH=/usr/share/tcltk/tcllib1.20
> 
> ```
>  active environment : None
>    user config file : /root/.condarc
> ```
> 
> populated config files : conda version : 4.5.4 conda-build version : not installed python version : 3.6.5.final.0 base environment : /usr/local (writable) channel URLs : https://repo.anaconda.com/pkgs/main/linux-64 https://repo.anaconda.com/pkgs/main/noarch https://repo.anaconda.com/pkgs/free/linux-64 https://repo.anaconda.com/pkgs/free/noarch https://repo.anaconda.com/pkgs/r/linux-64 https://repo.anaconda.com/pkgs/r/noarch https://repo.anaconda.com/pkgs/pro/linux-64 https://repo.anaconda.com/pkgs/pro/noarch package cache : /usr/local/pkgs /root/.conda/pkgs envs directories : /usr/local/envs /root/.conda/envs platform : linux-64 user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35 UID:GID : 0:0 netrc file : None offline mode : False
> 
> V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://repo.anaconda.com/pkgs/main/noarch/repodata.json.bz2 Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> If your current network has https://www.anaconda.com/ blocked, please file a support request with your network engineering team.
> 
> SSLError(MaxRetryError('HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))',),)
> 
> A reportable application error has occurred. Conda has prepared the above report. Upload did not complete.
> 
> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> `$ /usr/local/bin/conda update --channel defaults --all --yes`
> 
> environment variables: CIO_TEST= COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer COLAB_LANGUAGE_SERVER_PROXY= CONDA_ROOT=/usr/local LD_LIBRARY_PATH=/usr/lib64-nvidia LIBRARY_PATH=/usr/local/cuda/lib64/stubs PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl e-cloud-sdk/bin PYTHONPATH=/env/python PYTHONWARNINGS=ignore:::pip._internal.cli.base_command REQUESTS_CA_BUNDLE= SSL_CERT_FILE= TCLLIBPATH=/usr/share/tcltk/tcllib1.20
> 
> ```
>  active environment : None
>    user config file : /root/.condarc
> ```
> 
> populated config files : conda version : 4.5.4 conda-build version : not installed python version : 3.6.5.final.0 base environment : /usr/local (writable) channel URLs : https://repo.anaconda.com/pkgs/main/linux-64 https://repo.anaconda.com/pkgs/main/noarch https://repo.anaconda.com/pkgs/free/linux-64 https://repo.anaconda.com/pkgs/free/noarch https://repo.anaconda.com/pkgs/r/linux-64 https://repo.anaconda.com/pkgs/r/noarch https://repo.anaconda.com/pkgs/pro/linux-64 https://repo.anaconda.com/pkgs/pro/noarch package cache : /usr/local/pkgs /root/.conda/pkgs envs directories : /usr/local/envs /root/.conda/envs platform : linux-64 user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35 UID:GID : 0:0 netrc file : None offline mode : False
> 
> V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://repo.anaconda.com/pkgs/pro/noarch/repodata.json.bz2 Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> If your current network has https://www.anaconda.com/ blocked, please file a support request with your network engineering team.
> 
> SSLError(MaxRetryError('HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/pro/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))',),)
> 
> ## A reportable application error has occurred. Conda has prepared the above report.
> Upload did not complete.
> CalledProcessError Traceback (most recent call last) in <cell line: 1>() ----> 1 get_ipython().run_cell_magic('bash', '', 'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n')
> 
> 4 frames in shebang(self, line, cell)
> 
> [/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell) 243 sys.stderr.flush() 244 if args.raise_error and p.returncode!=0: --> 245 raise CalledProcessError(p.returncode, cell, output=out, stderr=err) 246 247 def _run_script(self, p, cell, to_close):
> 
> CalledProcessError: Command 'b'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n'' returned non-zero exit status 1.

working on it. Let's see

**Comment by punithan328** [comment]
> working on it. Let's see

Thanks for your response and consideration🙏

**Comment by punithan328** [comment]
> > @SwayamInSync
> > I'm getting tis error but one month before it worked perfectly what's the reason for this error 2024-04-16 03:06:55 (108 MB/s) - ‘Miniconda3-4.5.4-Linux-x86_64.sh’ saved [58468498/58468498]
> > Python 3.6.5 :: Anaconda, Inc.
> > # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> > `$ /usr/local/bin/conda install --channel defaults conda python=3.8 --yes`
> > environment variables: CIO_TEST= COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer COLAB_LANGUAGE_SERVER_PROXY= CONDA_ROOT=/usr/local LD_LIBRARY_PATH=/usr/lib64-nvidia LIBRARY_PATH=/usr/local/cuda/lib64/stubs PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl e-cloud-sdk/bin PYTHONPATH=/env/python PYTHONWARNINGS=ignore:::pip._internal.cli.base_command REQUESTS_CA_BUNDLE= SSL_CERT_FILE= TCLLIBPATH=/usr/share/tcltk/tcllib1.20
> > ```
> >  active environment : None
> >    user config file : /root/.condarc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > populated config files : conda version : 4.5.4 conda-build version : not installed python version : 3.6.5.final.0 base environment : /usr/local (writable) channel URLs : https://repo.anaconda.com/pkgs/main/linux-64 https://repo.anaconda.com/pkgs/main/noarch https://repo.anaconda.com/pkgs/free/linux-64 https://repo.anaconda.com/pkgs/free/noarch https://repo.anaconda.com/pkgs/r/linux-64 https://repo.anaconda.com/pkgs/r/noarch https://repo.anaconda.com/pkgs/pro/linux-64 https://repo.anaconda.com/pkgs/pro/noarch package cache : /usr/local/pkgs /root/.conda/pkgs envs directories : /usr/local/envs /root/.conda/envs platform : linux-64 user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35 UID:GID : 0:0 netrc file : None offline mode : False
> > V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
> > CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://repo.anaconda.com/pkgs/main/noarch/repodata.json.bz2 Elapsed: -
> > An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> > If your current network has https://www.anaconda.com/ blocked, please file a support request with your network engineering team.
> > SSLError(MaxRetryError('HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))',),)
> > A reportable application error has occurred. Conda has prepared the above report. Upload did not complete.
> > # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> > `$ /usr/local/bin/conda update --channel defaults --all --yes`
> > environment variables: CIO_TEST= COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer COLAB_LANGUAGE_SERVER_PROXY= CONDA_ROOT=/usr/local LD_LIBRARY_PATH=/usr/lib64-nvidia LIBRARY_PATH=/usr/local/cuda/lib64/stubs PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl e-cloud-sdk/bin PYTHONPATH=/env/python PYTHONWARNINGS=ignore:::pip._internal.cli.base_command REQUESTS_CA_BUNDLE= SSL_CERT_FILE= TCLLIBPATH=/usr/share/tcltk/tcllib1.20
> > ```
> >  active environment : None
> >    user config file : /root/.condarc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > populated config files : conda version : 4.5.4 conda-build version : not installed python version : 3.6.5.final.0 base environment : /usr/local (writable) channel URLs : https://repo.anaconda.com/pkgs/main/linux-64 https://repo.anaconda.com/pkgs/main/noarch https://repo.anaconda.com/pkgs/free/linux-64 https://repo.anaconda.com/pkgs/free/noarch https://repo.anaconda.com/pkgs/r/linux-64 https://repo.anaconda.com/pkgs/r/noarch https://repo.anaconda.com/pkgs/pro/linux-64 https://repo.anaconda.com/pkgs/pro/noarch package cache : /usr/local/pkgs /root/.conda/pkgs envs directories : /usr/local/envs /root/.conda/envs platform : linux-64 user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35 UID:GID : 0:0 netrc file : None offline mode : False
> > V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
> > CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://repo.anaconda.com/pkgs/pro/noarch/repodata.json.bz2 Elapsed: -
> > An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> > If your current network has https://www.anaconda.com/ blocked, please file a support request with your network engineering team.
> > SSLError(MaxRetryError('HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/pro/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))',),)
> > ## A reportable application error has occurred. Conda has prepared the above report.
> > Upload did not complete.
> > CalledProcessError Traceback (most recent call last) in <cell line: 1>() ----> 1 get_ipython().run_cell_magic('bash', '', 'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n')
> > 4 frames in shebang(self, line, cell)
> > [/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell) 243 sys.stderr.flush() 244 if args.raise_error and p.returncode!=0: --> 245 raise CalledProcessError(p.returncode, cell, output=out, stderr=err) 246 247 def _run_script(self, p, cell, to_close):
> > CalledProcessError: Command 'b'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n'' returned non-zero exit status 1.2024-04-16 03:06:55 (108 MB/s) - ‘Miniconda3-4.5.4-Linux-x86_64.sh’ saved [58468498/58468498]
> > Python 3.6.5 :: Anaconda, Inc.
> > # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> > `$ /usr/local/bin/conda install --channel defaults conda python=3.8 --yes`
> > environment variables: CIO_TEST= COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer COLAB_LANGUAGE_SERVER_PROXY= CONDA_ROOT=/usr/local LD_LIBRARY_PATH=/usr/lib64-nvidia LIBRARY_PATH=/usr/local/cuda/lib64/stubs PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl e-cloud-sdk/bin PYTHONPATH=/env/python PYTHONWARNINGS=ignore:::pip._internal.cli.base_command REQUESTS_CA_BUNDLE= SSL_CERT_FILE= TCLLIBPATH=/usr/share/tcltk/tcllib1.20
> > ```
> >  active environment : None
> >    user config file : /root/.condarc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > populated config files : conda version : 4.5.4 conda-build version : not installed python version : 3.6.5.final.0 base environment : /usr/local (writable) channel URLs : https://repo.anaconda.com/pkgs/main/linux-64 https://repo.anaconda.com/pkgs/main/noarch https://repo.anaconda.com/pkgs/free/linux-64 https://repo.anaconda.com/pkgs/free/noarch https://repo.anaconda.com/pkgs/r/linux-64 https://repo.anaconda.com/pkgs/r/noarch https://repo.anaconda.com/pkgs/pro/linux-64 https://repo.anaconda.com/pkgs/pro/noarch package cache : /usr/local/pkgs /root/.conda/pkgs envs directories : /usr/local/envs /root/.conda/envs platform : linux-64 user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35 UID:GID : 0:0 netrc file : None offline mode : False
> > V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
> > CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://repo.anaconda.com/pkgs/main/noarch/repodata.json.bz2 Elapsed: -
> > An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> > If your current network has https://www.anaconda.com/ blocked, please file a support request with your network engineering team.
> > SSLError(MaxRetryError('HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))',),)
> > A reportable application error has occurred. Conda has prepared the above report. Upload did not complete.
> > # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> > `$ /usr/local/bin/conda update --channel defaults --all --yes`
> > environment variables: CIO_TEST= COLAB_DEBUG_ADAPTER_MUX_PATH=/usr/local/bin/dap_multiplexer COLAB_LANGUAGE_SERVER_PROXY= CONDA_ROOT=/usr/local LD_LIBRARY_PATH=/usr/lib64-nvidia LIBRARY_PATH=/usr/local/cuda/lib64/stubs PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/us r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/googl e-cloud-sdk/bin PYTHONPATH=/env/python PYTHONWARNINGS=ignore:::pip._internal.cli.base_command REQUESTS_CA_BUNDLE= SSL_CERT_FILE= TCLLIBPATH=/usr/share/tcltk/tcllib1.20
> > ```
> >  active environment : None
> >    user config file : /root/.condarc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > populated config files : conda version : 4.5.4 conda-build version : not installed python version : 3.6.5.final.0 base environment : /usr/local (writable) channel URLs : https://repo.anaconda.com/pkgs/main/linux-64 https://repo.anaconda.com/pkgs/main/noarch https://repo.anaconda.com/pkgs/free/linux-64 https://repo.anaconda.com/pkgs/free/noarch https://repo.anaconda.com/pkgs/r/linux-64 https://repo.anaconda.com/pkgs/r/noarch https://repo.anaconda.com/pkgs/pro/linux-64 https://repo.anaconda.com/pkgs/pro/noarch package cache : /usr/local/pkgs /root/.conda/pkgs envs directories : /usr/local/envs /root/.conda/envs platform : linux-64 user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/6.1.58+ ubuntu/22.04 glibc/2.35 UID:GID : 0:0 netrc file : None offline mode : False
> > V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
> > CondaHTTPError: HTTP 000 CONNECTION FAILED for url https://repo.anaconda.com/pkgs/pro/noarch/repodata.json.bz2 Elapsed: -
> > An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way.
> > If your current network has https://www.anaconda.com/ blocked, please file a support request with your network engineering team.
> > SSLError(MaxRetryError('HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/pro/noarch/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))',),)
> > ## A reportable application error has occurred. Conda has prepared the above report.
> > Upload did not complete.
> > CalledProcessError Traceback (most recent call last) in <cell line: 1>() ----> 1 get_ipython().run_cell_magic('bash', '', 'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n')
> > 4 frames in shebang(self, line, cell)
> > [/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell) 243 sys.stderr.flush() 244 if args.raise_error and p.returncode!=0: --> 245 raise CalledProcessError(p.returncode, cell, output=out, stderr=err) 246 247 def _run_script(self, p, cell, to_close):
> > CalledProcessError: Command 'b'MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh\nMINICONDA_PREFIX=/usr/local\nwget [https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT\nchmod](https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT/nchmod) +x $MINICONDA_INSTALLER_SCRIPT\n./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX\nconda install --channel defaults conda python=3.8 --yes\nconda update --channel defaults --all --yes\n'' returned non-zero exit status 1.
> 
> working on it. Let's see

tomorrow i have final project review and presentation can u help if it is work on google collab is fine so that i can show the output HELP🙏

**Comment by sumit-jr** [comment]
@punithan328 did you manage to fix the error. Can you please help me out.

**Comment by sumit-jr** [comment]
@SwayamInSync how to fix environment error i.e. 
`conda update --channel defaults --all --yes`

**Comment by SwayamInSync** [comment]
Miniconda issue is fixed
